### ISSUE TITLE
Update http://schema.org references to https://schema.org, or ability to specify protocol

### ISSUE THREAD

**Issue by tarikhamilton** [bentaylor2/react-structured-data#12]
**Is your feature request related to a problem? Please describe.**
Not really. My Google Chrome testing tool is looking for `"@context": "https://schema.org"`, rather than http. Schema.org is officially https at the moment. https://schema.org/docs/faq.html#19

**Describe the solution you'd like**
While http://schema.org is totally fine for the unforeseeable future, https is pretty much standard and required today, so it'd be cool if maybe we could add a prop to the main component, like this: `<JSONLD protocol="https">`, or maybe set https as the default, but allow someone to manually set http as the protocol, in case there are any mixed content issues.

**Describe alternatives you've considered**
I've just edited the output to be https for my testing tool, or use Google's testing tool which doesn't care.

**Additional context**
https://schema.org/docs/faq.html#19

**Comment by bentaylor2** [comment]
0.0.13 should now point to https://schema.org. Let me know if it doesn't!
