### ISSUE TITLE
return encoded data i.e &quote;

### ISSUE THREAD

**Issue by hussain2y2** [bentaylor2/react-structured-data#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hussain2y2** [comment]
{&quot;@context&quot;:&quot;http://schema.org&quot;,&quot;@graph&quot; ................

Why it return like this when we view-source the page content.

**Comment by matthewlawson** [comment]
You can instruct the component to not sanitize the json by setting the `dangerouslyExposeHtml` on the root node eg:`<JSONLD dangerouslyExposeHtml>`

https://github.com/bentaylor2/react-structured-data#jsonld-node-proptypes
