### ISSUE TITLE
Bundle code not up to date

### ISSUE THREAD

**Issue by EricLambrecht** [bentaylor2/react-structured-data#14]
**Describe the bug**
There seems to be a problem with the bundling or deployment of this package.

The code I downloaded from the yarn registry does not seem to be the version I have installed.

I installed version **0.0.11**, but when I look at the source in my `npm_modules`, it seems to be from an older version, because the fix of #9 is not there. The source of JSONAbstractNode's `getChildJSON` function shows the following: 

```javascript
_createClass(JSONLDAbstractNode, [{
    key: 'getChildJSON',
    value: function getChildJSON(child, isCollection) {
      var ChildClass = child.type;

      var _child$props = child.props,
          children = _child$props.children,
          type = _child$props.type,
          id = _child$props.id,
          parentID = _child$props.parentID,
          schema = _objectWithoutProperties(_child$props, ['children', 'type', 'id', 'parentID']);

      if (!!parentID) schema = { '@id': parentID };
      if (!!id) schema = _extends({}, schema, {
        "@id": id
      });
      var newChildren = new ChildClass(child.props).getJSON(!!type || isCollection, schema);
      return !!type ? _extends(_defineProperty({}, type, newChildren)) : newChildren;
    }
  }
```

The line 
```javascript
if(!child) return '';
```
is missing! But it should be there since version **0.0.10**...

The `yarn.lock` file says I have version **0.0.11** installed, and also the `node_modules/react-structured-data/package.json` says `"version": "0.0.11"`. So I'm pretty sure, that's not the problem.

**To Reproduce**
1. Install `"react-structured-data": "0.0.11",`
2. Try to conditionally render children
3. See error `Uncaught [TypeError: Cannot read property 'type' of null]`
4. Look at source in `node_modules/react-structured-data/`

**Expected behavior**
I would expect the actual version `0.0.11` to be installed.

**Desktop:**
 - OS: macOS 10.14.2
 - Package manager: Yarn

**Comment by tstirrat15** [comment]
I'm seeing the same... This is frustrating.

**Comment by bentaylor2** [comment]
Sorry for late response. I don't have a lot of free time these days. I updated the bundle, not sure how it didn't make it in there. Should be good now, sorry for that! Please use version v0.0.12

**Comment by tstirrat15** [comment]
No worries. Thank you for pushing, @bentaylor2!

**Comment by dan-fein** [comment]
HI @bentaylor2 - It seems as though this still exists. I'm using .13 and just received Cannot read property 'children' of undefined. Any idea?
