### ISSUE TITLE
Unable to conditionally render child components

### ISSUE THREAD

**Issue by kahyoung-zz** [bentaylor2/react-structured-data#7]
In the given example:

```
<Generic type="localBusiness" jsonldtype="LocalBusiness" schema={localBusinessSchema}>
{ratingCount > 0 && <AggregateRating ratingCount={ratingCount} ratingValue={ratingValue} />}
</Generic>
```

The following error gets thrown:

```
Cannot read property 'children' of undefined
```

I think this should be permissible as certain schemas (e.g. aggregate rating) should not be rendered if there are no ratings, but there are currently no ways of conditionally rendering it.

**Comment by EricLambrecht** [comment]
Unfortunately this issue still persists, because the fix does seem to be included in **0.0.11** although it should be included since **0.0.10**. 

See #14
